# Generated by Django 5.1.1 on 2025-01-20 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('category', models.CharField(choices=[('カットソー', 'カットソー'), ('ブラウス', 'ブラウス'), ('ニット', 'ニット'), ('パンツ', 'パンツ'), ('スカート', 'スカート'), ('ワンピース', 'ワンピース'), ('シューズ', 'シューズ')], default='カットソー', max_length=10)),
                ('image', models.ImageField(blank=True, default='noImage.png', upload_to='')),
                ('season', models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall'), ('Winter', 'Winter')], default='Spring', max_length=10)),
                ('memo', models.CharField(default='', max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Coordination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('カジュアル', 'カジュアル'), ('仕事', '仕事'), ('マニッシュ', 'マニッシュ'), ('フェミニン', 'フェミニン')], default='カジュアル', max_length=10)),
                ('season', models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall'), ('Winter', 'Winter')], default='Spring', max_length=10)),
                ('coordination_image', models.ImageField(blank=True, default='noImage.png', upload_to='coordination_images/')),
                ('memo', models.CharField(default='', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('items', models.ManyToManyField(related_name='coordinations', to='coordination_app.item')),
            ],
        ),
    ]
